spring:
  datasource:
    mysplitter:
      configuration-file: classpath:mysplitter.yml
logging:
  level:
    com.zaxxer.hikari: off
    com.alibaba.druid: off
    com.mysplitter: debug
    root: info